package br.com.fiap.creditcardpayment.repository.orm;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "Sale")
public class SaleOrm {
    @Id
    @JsonIgnore
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @JsonProperty("merchant_order_id")
    @DynamoDBAttribute(attributeName = "merchant_order_id")
    private String merchantOrderId;

    @JsonProperty("payment_id")
    @DynamoDBAttribute(attributeName = "payment_id")
    private String paymentId;

    @JsonProperty("amount")
    @DynamoDBAttribute(attributeName = "amount")
    private Integer amount;

    @JsonProperty("status")
    @DynamoDBAttribute(attributeName = "status")
    private Integer status;

    public SaleOrm() {
    }

    public SaleOrm(
            String id,
            String merchantOrderId,
            String paymentId,
            Integer amount,
            Integer status) {
        this.id = id;
        this.merchantOrderId = merchantOrderId;
        this.paymentId = paymentId;
        this.amount = amount;
        this.status = status;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMerchantOrderId() {
        return merchantOrderId;
    }

    public void setMerchantOrderId(String merchantOrderId) {
        this.merchantOrderId = merchantOrderId;
    }

    public String getPaymentId() {
        return paymentId;
    }

    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
}
